name: food_home_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
    flutter:
      sdk: flutter
    firebase_core: ^4.2.1
    firebase_auth: ^6.1.2
    stacked: ^3.4.0 # Or latest
    stacked_services: ^1.6.0 # Or latest
    google_sign_in: ^7.2.0
    flutter_facebook_auth: ^7.1.2
    cloud_firestore: ^6.1.0
    sign_in_with_apple: ^7.0.1
    lucide_icons: ^0.257.0
    intl: ^0.20.2




dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true

